require "spec_helper"

describe Takky::Uploader::DataUriUploader do
  include TakkySupport

  let(:uri) {
    <<-EOF
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wgARCAAGAAsDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EABQBAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhADEAAAATQZT//EABgQAQADAQAAAAAAAAAAAAAAAAUBBAcG/9oACAEBAAEFAup0hBpmhtZ00//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQMBAT8BP//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQIBAT8BP//EACIQAAEEAAUFAAAAAAAAAAAAAAQBAgMRABITUWEUISMxUv/aAAgBAQAGPwKEkOWQEYV+YaNF739O3Xj1S1vcXWhlNLryaDWqy+Ldj//EABoQAQEAAwEBAAAAAAAAAAAAAAERITFhAFH/2gAIAQEAAT8h64hSD5oKbBMqvHPGo7MwY7jqysr/AP/aAAwDAQACAAMAAAAQA//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQMBAT8QP//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQIBAT8QP//EABcQAQEBAQAAAAAAAAAAAAAAAAERACH/2gAIAQEAAT8QaoEEclEr9qAo3niAXwqJPAIFpiv/2Q==
  EOF
  }

  subject(:uploader) { described_class.new(TakkySupport::FakeAttachment, 1, uri) }

  describe "#file_from_data_uri" do
    it "generates a file" do
      source = image_fixture("triangle.jpg")

      from_uri = uploader.file_from_data_uri(uri)
      expect(identical_files?(from_uri.path, source)).to equal true
      from_uri.close
      from_uri.unlink
    end
  end
end
